version: '2.1'

services:

  score-series:
    container_name: score-series-hise
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - score
    depends_on:
      - score-db
      - score-nginx

  score-nginx:
    image: nginx:alpine
    container_name: score-nginx
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - score

  score-db:
    container_name: score-db
    image: mariadb:10.2.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: score
    volumes:
      - score-data:/var/lib/mysql
    networks:
      - score



volumes:
  score-data:

networks:
  score:
    driver: bridge
    name: score

